<ul>
<li>version 1.0 - March, 2009
    <ul>
      <li>Initial Release</li>
    </ul></li>
<li>version 1.0.1 - March, 2009
    <ul>
      <li>Minor template change.</li>
      <li>Set a default success message.</li>
    </ul></li>
<li>version 1.0.2 - April, 2009
    <ul>
      <li>Fix minor issue with permissions checking.</li>
    </ul></li>
</ul>
<li>version 1.0.4 - October, 2009
    <ul>
      <li>Minor bug fixes.</li>
    </ul></li>
<li>version 1.0.6 - March, 2010
    <ul>
      <li>Updated to work with new CGExtensions.</li>
    </ul>
</li>
<li>version 1.1 - May, 2010
    <ul>
    <li>Many new parameters, and options.</li>
    </ul>
</li>
<li>version 1.2 - May, 2010
    <ul>
    <li>Fixes security vulnerability.</li>
    </ul>
</li>
<li>version 1.3.2 - March, 2011
    <ul>
    <li>Move changelog out of lang file.</li>
    <li>Numerous bug fixes and enhancements.</li>
    </ul>
</li>
<li>version 1.3.3 - March, 2011
    <ul>
    <li>Fixes upgrade to add the notified field.</li>
    <li>Update dependencies</li>
    </ul>
</li>
<li>version 1.3.4 - May, 2011
    <ul>
    <li>Bug Fixes.</li>
    </ul>
</li>
<li>version 1.3.5 - June, 2011
    <ul>
    <li>Bug Fixes.</li>
    </ul>
</li>
<li>Version 1.3.6 - July, 2011
  <ul>
    <li>Bug fixes.</li>
  </ul>
</li>
<li>Version 1.3.7 - August, 2011
  <ul>
    <li>Bug fixes... now should work with CMSMS 1.10</li>
    <li>Adds noredirect param.</li>
  </ul>
</li>
<li>Version 1.3.8 - September, 2011
  <ul>
    <li>Bug fixes... </li>
  </ul>
</li>
<li>Version 1.4 - September, 2011
  <ul>
     <li>Adds automatic moderation detection</li>
  </ul>
</li>
<li>Version 1.5 - October, 2011
  <ul>
     <li>Re-adds the origurl thing (but as a property of the comment).</li>
  </ul>
</li>
<li>Version 1.5.1 - October, 2011
  <ul>
     <li>Adjust the origurl to be the feedback_origurl if available.</li>
  </ul>
</li>
<li>Version 1.5.2 - October, 2011
  <ul>
     <li>Adds the redirectextra param for the default action.</li>
  </ul>
</li>
<li>Version 1.5.3 - October, 2011
  <ul>
     <li>Fixes CMSMS 1.10 problem.</li>
  </ul>
</li>
<li>Version 1.5.4 - November, 2011
  <ul>
     <li>E_STRICT fixes.</li>
  </ul>
</li>
</ul>
