<?php /* Smarty version 2.6.26, created on 2011-10-29 05:37:09
         compiled from tpl_head:22 */

$this->_cache_serials['E:\WEB\CMS\simple\tmp\templates_c\%%19^194^194941AA%%tpl_head%3A22.inc'] = '2e0b55c2414d452b9c468e927c048268';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'tpl_head:22', 4, false),array('function', 'sitename', 'tpl_head:22', 4, false),array('function', 'metadata', 'tpl_head:22', 7, false),array('function', 'cms_stylesheet', 'tpl_head:22', 10, false),array('function', 'cms_selflink', 'tpl_head:22', 13, false),)), $this); ?>
<?php
function _smarty_tplfunc_2e0b55c2414d452b9c468e927c048268_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e0b55c2414d452b9c468e927c048268','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2e0b55c2414d452b9c468e927c048268_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e0b55c2414d452b9c468e927c048268','1');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_2e0b55c2414d452b9c468e927c048268_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e0b55c2414d452b9c468e927c048268','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2e0b55c2414d452b9c468e927c048268_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e0b55c2414d452b9c468e927c048268','3');echo smarty_cms_function_cms_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2e0b55c2414d452b9c468e927c048268_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e0b55c2414d452b9c468e927c048268','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_2e0b55c2414d452b9c468e927c048268_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e0b55c2414d452b9c468e927c048268','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_2e0b55c2414d452b9c468e927c048268_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e0b55c2414d452b9c468e927c048268','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
