<?php /* Smarty version 2.6.26, created on 2011-11-12 04:15:01
         compiled from tpl_head:16 */

$this->_cache_serials['E:\WEB\CMSDepdagri\Source\simple\tmp\templates_c\%%35^350^3509D670%%tpl_head%3A16.inc'] = '7a90f2334de818ca3135a3123956fb28';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'sitename', 'tpl_head:16', 2, false),array('function', 'title', 'tpl_head:16', 2, false),array('function', 'metadata', 'tpl_head:16', 5, false),array('function', 'cms_stylesheet', 'tpl_head:16', 8, false),array('function', 'cms_selflink', 'tpl_head:16', 11, false),)), $this); ?>
<?php
function _smarty_tplfunc_7a90f2334de818ca3135a3123956fb28_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7a90f2334de818ca3135a3123956fb28','0');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_7a90f2334de818ca3135a3123956fb28_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7a90f2334de818ca3135a3123956fb28','1');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7a90f2334de818ca3135a3123956fb28_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7a90f2334de818ca3135a3123956fb28','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7a90f2334de818ca3135a3123956fb28_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7a90f2334de818ca3135a3123956fb28','3');echo smarty_cms_function_cms_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7a90f2334de818ca3135a3123956fb28_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7a90f2334de818ca3135a3123956fb28','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_7a90f2334de818ca3135a3123956fb28_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7a90f2334de818ca3135a3123956fb28','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_7a90f2334de818ca3135a3123956fb28_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7a90f2334de818ca3135a3123956fb28','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
