<?php /* Smarty version 2.6.26, created on 2011-10-29 05:00:42
         compiled from pagedefaults.tpl */

$this->_cache_serials['E:\WEB\CMS\simple\tmp\templates_c\%%51^51A^51AB8697%%pagedefaults.tpl.inc'] = '4cbc72690956776a1620710f8af4bcb8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'lang', 'pagedefaults.tpl', 3, false),array('function', 'html_options', 'pagedefaults.tpl', 21, false),)), $this); ?>
<?php
function _smarty_tplfunc_4cbc72690956776a1620710f8af4bcb8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4cbc72690956776a1620710f8af4bcb8','0');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['all_contenttypes'],'selected' => $_smarty->_tpl_vars['default_contenttype']), $_smarty);
}



?>
