<?php /* Smarty version 2.6.26, created on 2011-10-29 05:37:08
         compiled from tpl_top:22 */

$this->_cache_serials['E:\WEB\CMS\simple\tmp\templates_c\%%52^52E^52E7C88B%%tpl_top%3A22.inc'] = '5264944129d7d3f7f5c727810d1804d4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:22', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_5264944129d7d3f7f5c727810d1804d4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5264944129d7d3f7f5c727810d1804d4','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
