<?php /* Smarty version 2.6.26, created on 2011-10-29 05:00:51
         compiled from systeminfo.tpl */

$this->_cache_serials['E:\WEB\CMS\simple\tmp\templates_c\%%54^54D^54D58E70%%systeminfo.tpl.inc'] = 'b0016bda300f4ea51828fb0ac5674f47';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'si_lang', 'systeminfo.tpl', 3, false),array('function', 'cycle', 'systeminfo.tpl', 19, false),array('modifier', 'default', 'systeminfo.tpl', 57, false),array('modifier', 'lower', 'systeminfo.tpl', 110, false),)), $this); ?>
<?php
function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','0');echo systeminfo_lang(array('a' => 'copy_paste_forum'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','1');echo systeminfo_lang(array('a' => 'help_systeminformation'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','2');echo systeminfo_lang(array('a' => 'cms_install_information'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','3');echo systeminfo_lang(array('a' => 'cms_install_information'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','4');echo smarty_function_cycle(array('values' => 'row1,row2'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','5');echo systeminfo_lang(array('a' => 'cms_version'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','6');echo systeminfo_lang(array('a' => 'installed_modules'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','7');echo systeminfo_lang(array('a' => 'installed_modules'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','8');echo smarty_function_cycle(array('values' => 'row1,row2'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','9');echo systeminfo_lang(array('a' => 'config_information'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','10');echo systeminfo_lang(array('a' => 'config_information'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','11');echo smarty_function_cycle(array('values' => 'row1,row2'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_12(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','12');echo systeminfo_lang(array('a' => 'php_information'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_13(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','13');echo systeminfo_lang(array('a' => 'php_information'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_14(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','14');echo smarty_function_cycle(array('values' => 'row1,row2'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_15(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','15');echo systeminfo_lang(array('a' => $_smarty->_tpl_vars['key']), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_16(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','16');echo systeminfo_lang(array('a' => 'server_information'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_17(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','17');echo systeminfo_lang(array('a' => 'server_information'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_18(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','18');echo smarty_function_cycle(array('values' => 'row1,row2'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_19(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','19');echo systeminfo_lang(array('a' => $_smarty->_tpl_vars['key']), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_20(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','20');echo systeminfo_lang(array('a' => 'permission_information'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_21(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','21');echo systeminfo_lang(array('a' => 'permission_information'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_22(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','22');echo smarty_function_cycle(array('values' => 'row1,row2'), $_smarty);
}


function _smarty_tplfunc_b0016bda300f4ea51828fb0ac5674f47_23(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0016bda300f4ea51828fb0ac5674f47','23');echo systeminfo_lang(array('a' => 'back'), $_smarty);
}



?>
