<?php /* Smarty version 2.6.26, created on 2011-11-13 17:18:24
         compiled from listcssassoc.tpl */

$this->_cache_serials['E:\WEB\CMSDepdagri\Source\simple\tmp\templates_c\%%64^64F^64FC46BF%%listcssassoc.tpl.inc'] = 'be874feb58f02fbb09f0f8ca19f757f7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cycle', 'listcssassoc.tpl', 19, false),)), $this); ?>
<?php
function _smarty_tplfunc_be874feb58f02fbb09f0f8ca19f757f7_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('be874feb58f02fbb09f0f8ca19f757f7','0');echo smarty_function_cycle(array('values' => 'row1,row2','assign' => 'currow'), $_smarty);
}



?>
