<?php /* Smarty version 2.6.26, created on 2011-11-13 17:25:09
         compiled from tpl_head:23 */

$this->_cache_serials['E:\WEB\CMSDepdagri\Source\simple\tmp\templates_c\%%6E^6E4^6E4E713C%%tpl_head%3A23.inc'] = '2a6af5f24daea56540c612f614259971';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'sitename', 'tpl_head:23', 2, false),array('function', 'title', 'tpl_head:23', 2, false),array('function', 'metadata', 'tpl_head:23', 5, false),array('function', 'cms_stylesheet', 'tpl_head:23', 8, false),array('function', 'cms_selflink', 'tpl_head:23', 11, false),)), $this); ?>
<?php
function _smarty_tplfunc_2a6af5f24daea56540c612f614259971_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a6af5f24daea56540c612f614259971','0');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_2a6af5f24daea56540c612f614259971_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a6af5f24daea56540c612f614259971','1');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2a6af5f24daea56540c612f614259971_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a6af5f24daea56540c612f614259971','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2a6af5f24daea56540c612f614259971_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a6af5f24daea56540c612f614259971','3');echo smarty_cms_function_cms_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2a6af5f24daea56540c612f614259971_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a6af5f24daea56540c612f614259971','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_2a6af5f24daea56540c612f614259971_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a6af5f24daea56540c612f614259971','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_2a6af5f24daea56540c612f614259971_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a6af5f24daea56540c612f614259971','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
