<?php /* Smarty version 2.6.26, created on 2011-11-12 04:15:00
         compiled from tpl_top:16 */

$this->_cache_serials['E:\WEB\CMSDepdagri\Source\simple\tmp\templates_c\%%7E^7EA^7EA75F51%%tpl_top%3A16.inc'] = '39882f2aaba077ba2016b6c31b651410';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:16', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_39882f2aaba077ba2016b6c31b651410_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('39882f2aaba077ba2016b6c31b651410','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
