<?php /* Smarty version 2.6.26, created on 2011-10-29 05:02:22
         compiled from content:content_en */

$this->_cache_serials['E:\WEB\CMS\simple\tmp\templates_c\15^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'c36144d9c424efcb68bddf7eaf7d1305';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_c36144d9c424efcb68bddf7eaf7d1305_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c36144d9c424efcb68bddf7eaf7d1305','0');echo smarty_cms_function_cms_selflink(array('ext' => "http://wiki.cmsmadesimple.org/",'title' => 'CMS Made Simple Documentation','text' => 'documentation','target' => '_blank'), $_smarty);
}


function _smarty_tplfunc_c36144d9c424efcb68bddf7eaf7d1305_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c36144d9c424efcb68bddf7eaf7d1305','1');echo smarty_cms_function_cms_selflink(array('ext' => "http://forum.cmsmadesimple.org",'title' => 'CMS Made Simple Forum','text' => 'forum','target' => '_blank'), $_smarty);
}


function _smarty_tplfunc_c36144d9c424efcb68bddf7eaf7d1305_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c36144d9c424efcb68bddf7eaf7d1305','2');echo smarty_cms_function_cms_selflink(array('ext' => "http://www.cmsmadesimple.org/support/irc",'title' => 'Information about the CMS Made Simple IRC channel','text' => 'IRC','target' => '_blank'), $_smarty);
}


function _smarty_tplfunc_c36144d9c424efcb68bddf7eaf7d1305_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c36144d9c424efcb68bddf7eaf7d1305','3');echo smarty_cms_function_cms_selflink(array('ext' => "http://www.gnu.org/licenses/licenses.html#GPL",'title' => 'General Public License','text' => 'GPL','target' => '_blank'), $_smarty);
}



?>
