<?php /* Smarty version 2.6.26, created on 2011-11-13 07:53:07
         compiled from content:content_en */

$this->_cache_serials['E:\WEB\CMSDepdagri\Source\simple\tmp\templates_c\61^%%70^707^707A8977%%content%3Acontent_en.inc'] = '3919cfa824b24c983c07c35770a4e78d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 13, false),)), $this); ?>
<?php
function _smarty_tplfunc_3919cfa824b24c983c07c35770a4e78d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3919cfa824b24c983c07c35770a4e78d','0');echo smarty_cms_function_cms_selflink(array('href' => 'indracatri'), $_smarty);
}


function _smarty_tplfunc_3919cfa824b24c983c07c35770a4e78d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3919cfa824b24c983c07c35770a4e78d','1');echo smarty_cms_function_cms_selflink(array('href' => 'ismanimran'), $_smarty);
}


function _smarty_tplfunc_3919cfa824b24c983c07c35770a4e78d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3919cfa824b24c983c07c35770a4e78d','2');echo smarty_cms_function_cms_selflink(array('href' => 'ruzaidin'), $_smarty);
}


function _smarty_tplfunc_3919cfa824b24c983c07c35770a4e78d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3919cfa824b24c983c07c35770a4e78d','3');echo smarty_cms_function_cms_selflink(array('href' => 'aswan'), $_smarty);
}



?>
