<?php /* Smarty version 2.6.26, created on 2011-11-13 07:56:26
         compiled from module_file_tpl:News%3Bcustomfieldstab.tpl */

$this->_cache_serials['E:\WEB\CMSDepdagri\Source\simple\tmp\templates_c\News^%%DC^DCB^DCB07EC3%%module_file_tpl%3ANews%3Bcustomfieldstab.tpl.inc'] = '59322bd7b03adce22e02972f90904589';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cycle', 'module_file_tpl:News;customfieldstab.tpl', 36, false),)), $this); ?>
<?php
function _smarty_tplfunc_59322bd7b03adce22e02972f90904589_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('59322bd7b03adce22e02972f90904589','0');echo smarty_function_cycle(array('values' => "row1,row2",'assign' => 'rowclass'), $_smarty);
}



?>
