<?php /* Smarty version 2.6.26, created on 2011-11-13 17:25:09
         compiled from tpl_body:23 */

$this->_cache_serials['E:\WEB\CMSDepdagri\Source\simple\tmp\templates_c\%%01^013^01360D26%%tpl_body%3A23.inc'] = '71ce5c93a78d8dfcb621e160c9c3a158';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'tpl_body:23', 17, false),array('function', 'content', 'tpl_body:23', 18, false),)), $this); ?>
<?php
function _smarty_tplfunc_71ce5c93a78d8dfcb621e160c9c3a158_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('71ce5c93a78d8dfcb621e160c9c3a158','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_71ce5c93a78d8dfcb621e160c9c3a158_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('71ce5c93a78d8dfcb621e160c9c3a158','1');echo smarty_cms_function_content(array(), $_smarty);
}



?>
