<?php /* Smarty version 2.6.26, created on 2011-11-12 08:41:35
         compiled from tpl_body:23 */

$this->_cache_serials['E:\WEB\CMSDepdagri\Source\simple\tmp\templates_c\%%01^013^01360D26%%tpl_body%3A23.inc'] = '21306c83f1dfc8cbcde47336a36fd187';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'tpl_body:23', 17, false),array('function', 'content', 'tpl_body:23', 18, false),)), $this); ?>
<?php
function _smarty_tplfunc_21306c83f1dfc8cbcde47336a36fd187_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('21306c83f1dfc8cbcde47336a36fd187','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_21306c83f1dfc8cbcde47336a36fd187_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('21306c83f1dfc8cbcde47336a36fd187','1');echo smarty_cms_function_content(array(), $_smarty);
}



?>
