<?php /* Smarty version 2.6.26, created on 2011-10-29 05:12:25
         compiled from listtags.tpl */

$this->_cache_serials['E:\WEB\CMS\simple\tmp\templates_c\%%1B^1B5^1B53D2DB%%listtags.tpl.inc'] = '3cdca51a01701661453009ade6823973';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'lang', 'listtags.tpl', 7, false),array('function', 'cycle', 'listtags.tpl', 29, false),)), $this); ?>
<?php
function _smarty_tplfunc_3cdca51a01701661453009ade6823973_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3cdca51a01701661453009ade6823973','0');echo smarty_function_cycle(array('values' => "row1,row2",'assign' => 'rowclass'), $_smarty);
}



?>
