<?php /* Smarty version 2.6.26, created on 2011-10-29 05:29:41
         compiled from siteprefs.tpl */

$this->_cache_serials['E:\WEB\CMS\simple\tmp\templates_c\%%1B^1B2^1B2DE232%%siteprefs.tpl.inc'] = '90358ce243ed5689911b7a1330176ffa';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'html_options', 'siteprefs.tpl', 26, false),array('modifier', 'lang', 'siteprefs.tpl', 83, false),)), $this); ?>
<?php
function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','0');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['languages'],'selected' => $_smarty->_tpl_vars['frontendlang']), $_smarty);
}


function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','1');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['wysiwyg'],'selected' => $_smarty->_tpl_vars['frontendwysiwyg']), $_smarty);
}


function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','2');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['themes'],'selected' => $_smarty->_tpl_vars['logintheme']), $_smarty);
}


function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','3');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['search_modules'],'selected' => $_smarty->_tpl_vars['search_module']), $_smarty);
}


function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','4');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['titlemenu'],'selected' => $_smarty->_tpl_vars['listcontent_showtitle']), $_smarty);
}


function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','5');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['listcontent_showalias']), $_smarty);
}


function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','6');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['listcontent_showurl']), $_smarty);
}


function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','7');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['content_autocreate_urls']), $_smarty);
}


function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','8');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['content_autocreate_flaturls']), $_smarty);
}


function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','9');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['content_mandatory_urls']), $_smarty);
}


function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','10');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['all_contenttypes'],'selected' => $_smarty->_tpl_vars['disallowed_contenttypes']), $_smarty);
}


function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','11');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['all_attributes'],'selected' => $_smarty->_tpl_vars['basic_attributes']), $_smarty);
}


function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_12(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','12');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['pseudocron_options'],'selected' => $_smarty->_tpl_vars['pseudocron_granularity']), $_smarty);
}


function _smarty_tplfunc_90358ce243ed5689911b7a1330176ffa_13(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90358ce243ed5689911b7a1330176ffa','13');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['adminlog_options'],'selected' => $_smarty->_tpl_vars['adminlog_lifetime']), $_smarty);
}



?>
