<?php /* Smarty version 2.6.26, created on 2011-11-12 08:41:35
         compiled from tpl_top:23 */

$this->_cache_serials['E:\WEB\CMSDepdagri\Source\simple\tmp\templates_c\%%25^25E^25E0F81D%%tpl_top%3A23.inc'] = '33d417183a20f07635aa5b1a592e2d7d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:23', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_33d417183a20f07635aa5b1a592e2d7d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('33d417183a20f07635aa5b1a592e2d7d','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
