<?php /* Smarty version 2.6.26, created on 2011-11-12 04:15:01
         compiled from tpl_body:16 */

$this->_cache_serials['E:\WEB\CMSDepdagri\Source\simple\tmp\templates_c\%%5A^5A7^5A71AA6A%%tpl_body%3A16.inc'] = '6a86799e64eeb41ade65e1390a12d148';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'anchor', 'tpl_body:16', 7, false),array('function', 'sitename', 'tpl_body:16', 19, false),array('function', 'cms_selflink', 'tpl_body:16', 22, false),array('function', 'menu', 'tpl_body:16', 31, false),array('function', 'search', 'tpl_body:16', 38, false),array('function', 'breadcrumbs', 'tpl_body:16', 48, false),array('function', 'content', 'tpl_body:16', 60, false),array('function', 'news', 'tpl_body:16', 65, false),array('function', 'print', 'tpl_body:16', 78, false),array('function', 'title', 'tpl_body:16', 79, false),array('function', 'global_content', 'tpl_body:16', 117, false),)), $this); ?>
<?php
function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','0');echo smarty_cms_function_anchor(array('anchor' => 'menu_vert','title' => 'Skip to navigation','accesskey' => 'n','text' => 'Skip to navigation'), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','1');echo smarty_cms_function_anchor(array('anchor' => 'main','title' => 'Skip to content','accesskey' => 's','text' => 'Skip to content'), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','2');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','3');echo smarty_cms_function_cms_selflink(array('dir' => 'start','text' => ($_smarty->_tpl_vars['sitename'])), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','4');echo smarty_cms_function_menu(array('loadprops' => 0,'template' => 'cssmenu.tpl'), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','5');echo smarty_cms_function_search(array(), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','6');echo smarty_cms_function_breadcrumbs(array('starttext' => 'You are here','root' => 'Home','delimiter' => '&raquo;'), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','7');echo smarty_cms_function_content(array('block' => 'Sidebar'), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','8');echo smarty_cms_function_news(array('number' => '3','detailpage' => 'news'), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','9');echo smarty_cms_function_print(array('showbutton' => true,'script' => true), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','10');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','11');echo smarty_cms_function_content(array(), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_12(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','12');echo smarty_cms_function_anchor(array('anchor' => 'main','text' => '^ Top'), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_13(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','13');echo smarty_cms_function_cms_selflink(array('dir' => 'previous','label' => "Previous page: "), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_14(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','14');echo smarty_cms_function_cms_selflink(array('dir' => 'next'), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_15(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','15');echo smarty_cms_function_menu(array('loadprops' => 0), $_smarty);
}


function _smarty_tplfunc_6a86799e64eeb41ade65e1390a12d148_16(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a86799e64eeb41ade65e1390a12d148','16');echo smarty_cms_function_global_content(array('name' => 'footer'), $_smarty);
}



?>
