<?php /* Smarty version 2.6.26, created on 2011-11-12 08:41:35
         compiled from tpl_head:23 */

$this->_cache_serials['E:\WEB\CMSDepdagri\Source\simple\tmp\templates_c\%%6E^6E4^6E4E713C%%tpl_head%3A23.inc'] = 'd2ad9375d262033ecd584da4484de92c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'sitename', 'tpl_head:23', 2, false),array('function', 'title', 'tpl_head:23', 2, false),array('function', 'metadata', 'tpl_head:23', 5, false),array('function', 'cms_stylesheet', 'tpl_head:23', 8, false),array('function', 'cms_selflink', 'tpl_head:23', 11, false),)), $this); ?>
<?php
function _smarty_tplfunc_d2ad9375d262033ecd584da4484de92c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d2ad9375d262033ecd584da4484de92c','0');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_d2ad9375d262033ecd584da4484de92c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d2ad9375d262033ecd584da4484de92c','1');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d2ad9375d262033ecd584da4484de92c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d2ad9375d262033ecd584da4484de92c','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d2ad9375d262033ecd584da4484de92c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d2ad9375d262033ecd584da4484de92c','3');echo smarty_cms_function_cms_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d2ad9375d262033ecd584da4484de92c_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d2ad9375d262033ecd584da4484de92c','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_d2ad9375d262033ecd584da4484de92c_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d2ad9375d262033ecd584da4484de92c','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_d2ad9375d262033ecd584da4484de92c_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d2ad9375d262033ecd584da4484de92c','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
