<?php /* Smarty version 2.6.26, created on 2011-11-13 17:12:23
         compiled from tpl_top:16 */

$this->_cache_serials['E:\WEB\CMSDepdagri\Source\simple\tmp\templates_c\%%7E^7EA^7EA75F51%%tpl_top%3A16.inc'] = '074041418574bf0e564fab8e4da5f18b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:16', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_074041418574bf0e564fab8e4da5f18b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('074041418574bf0e564fab8e4da5f18b','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
