<?php /* Smarty version 2.6.26, created on 2011-10-29 05:07:40
         compiled from content:content_en */

$this->_cache_serials['E:\WEB\CMS\simple\tmp\templates_c\56^%%70^707^707A8977%%content%3Acontent_en.inc'] = '87eb038c7fbdd117a0a48629b897a57f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'Gallery', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_87eb038c7fbdd117a0a48629b897a57f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('87eb038c7fbdd117a0a48629b897a57f','0');echo $_smarty->_plugins['function']['Gallery'][0][0]->function_plugin(array(), $_smarty);
}



?>
