<?php /* Smarty version 2.6.26, created on 2011-11-12 02:28:51
         compiled from content:content_en */

$this->_cache_serials['E:\WEB\CMSDepdagri\Source\simple\tmp\templates_c\56^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'dd279c3583b0a47a6de4a9e5f090438c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'Gallery', 'content:content_en', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_dd279c3583b0a47a6de4a9e5f090438c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dd279c3583b0a47a6de4a9e5f090438c','0');echo $_smarty->_plugins['function']['Gallery'][0][0]->function_plugin(array('template' => 'Fancybox'), $_smarty);
}



?>
