<?php /* Smarty version 2.6.26, created on 2011-10-29 05:08:29
         compiled from module_file_tpl:FileManager%3Bfilemanager.tpl */

$this->_cache_serials['E:\WEB\CMS\simple\tmp\templates_c\FileManager^%%8E^8E9^8E95A59C%%module_file_tpl%3AFileManager%3Bfilemanager.tpl.inc'] = 'e2bd47ade771eb7b7cd605961fe051b7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cycle', 'module_file_tpl:FileManager;filemanager.tpl', 45, false),array('modifier', 'cms_date_format', 'module_file_tpl:FileManager;filemanager.tpl', 55, false),)), $this); ?>
<?php
function _smarty_tplfunc_e2bd47ade771eb7b7cd605961fe051b7_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e2bd47ade771eb7b7cd605961fe051b7','0');echo smarty_function_cycle(array('values' => "row1,row2",'assign' => 'rowclass'), $_smarty);
}



?>
